"""
DiskMind – AI Recommendation Engine
Generates risk-aware, explainable cleanup/archive recommendations.
"""
from __future__ import annotations

import time
from typing import Any


# ── Recommendation generation ──────────────────────────────────────────────────

async def generate_recommendations(db) -> list[dict[str, Any]]:
    """
    Build recommendations from intelligence engine outputs.
    Priority order: duplicates → caches → logs → build artifacts → inactive files
    Returns list of recommendation dicts.
    """
    from backend.database.database import fetchall, execute

    recommendations = []

    # 1. Duplicate file groups
    dup_groups = await fetchall(db, """
        SELECT dg.content_hash, dg.total_wasted_bytes, dg.file_count,
               dg.file_type, dg.confidence
        FROM duplicate_groups dg
        WHERE dg.total_wasted_bytes > 1048576
        ORDER BY dg.total_wasted_bytes DESC
        LIMIT 20
    """)

    for g in dup_groups:
        # Get paths in this group
        files = await fetchall(db, """
            SELECT path, size_bytes FROM files
            WHERE duplicate_group = ? ORDER BY accessed_at DESC
        """, (g["content_hash"],))

        if len(files) < 2:
            continue

        kept = files[0]["path"]  # most recently accessed = keep
        duplicates = [f["path"] for f in files[1:]]
        size = g["total_wasted_bytes"]

        reason = f"{g['file_count']} identical {g['file_type']} files detected"
        explanation = (
            f"SHA-256 hash confirmed: {g['file_count']} exact copies. "
            f"Keeping most recently accessed copy at {kept}. "
            f"Moving {len(duplicates)} duplicate(s) to Trash saves {_fmt_size(size)}."
        )

        rec = {
            "action": "CLEANUP",
            "target_path": json_paths(duplicates),
            "target_type": "duplicate_group",
            "size_bytes": int(size),
            "confidence": round(float(g["confidence"]), 3),
            "risk_level": "LOW",
            "risk_score": 5.0,
            "reason": reason,
            "explanation": explanation,
            "duplicate_group": g["content_hash"],
            "category": "duplicates",
        }
        recommendations.append(rec)

    # 2. Large cache directories
    cache_files = await fetchall(db, """
        SELECT SUM(size_bytes) as total, file_type, application,
               SUBSTR(path, 1, LENGTH(path) - LENGTH(filename) - 1) as dir
        FROM files
        WHERE file_type = 'cache' AND risk_level IN ('LOW', 'MEDIUM')
        GROUP BY SUBSTR(path, 1, 50), application
        HAVING SUM(size_bytes) > 10485760
        ORDER BY total DESC
        LIMIT 10
    """)

    cache_totals: dict[str, int] = {}
    for c in cache_files:
        app = c["application"] or "general"
        cache_totals[app] = cache_totals.get(app, 0) + (c["total"] or 0)

    for app, total_size in cache_totals.items():
        if total_size < 10_000_000:
            continue
        rec = {
            "action": "CLEANUP",
            "target_path": f"[{app} cache files]",
            "target_type": "file_type",
            "size_bytes": int(total_size),
            "confidence": 0.95,
            "risk_level": "LOW",
            "risk_score": 8.0,
            "reason": f"{app} cache consuming {_fmt_size(total_size)}",
            "explanation": (
                f"Application cache files for {app}. These are auto-regenerated "
                f"by {app} on next use. Safe to remove."
            ),
            "duplicate_group": None,
            "category": "cache",
        }
        recommendations.append(rec)

    # 3. Build artifacts
    build_files = await fetchall(db, """
        SELECT SUM(size_bytes) as total, application
        FROM files
        WHERE file_type = 'build_artifact' AND risk_level = 'LOW'
        GROUP BY application
        HAVING SUM(size_bytes) > 52428800
        ORDER BY total DESC
        LIMIT 5
    """)

    for b in build_files:
        if not b["total"]:
            continue
        app = b["application"] or "build"
        rec = {
            "action": "CLEANUP",
            "target_path": f"[{app} build artifacts]",
            "target_type": "file_type",
            "size_bytes": int(b["total"]),
            "confidence": 0.88,
            "risk_level": "LOW",
            "risk_score": 10.0,
            "reason": f"{app} build artifacts ({_fmt_size(b['total'])})",
            "explanation": (
                f"Compiled/built output files for {app}. "
                "These can be regenerated by rebuilding the project."
            ),
            "duplicate_group": None,
            "category": "build_artifact",
        }
        recommendations.append(rec)

    # 4. Highly inactive large files
    inactive = await fetchall(db, """
        SELECT path, filename, size_bytes, inactivity_score, risk_level, file_type
        FROM files
        WHERE inactivity_score >= 75 AND size_bytes >= 104857600
              AND risk_level = 'LOW' AND is_protected = 0
        ORDER BY size_bytes DESC
        LIMIT 10
    """)

    for f in inactive:
        confidence = round(f["inactivity_score"] / 100.0 * 0.85, 3)
        rec = {
            "action": "ARCHIVE",
            "target_path": f["path"],
            "target_type": "file",
            "size_bytes": int(f["size_bytes"]),
            "confidence": confidence,
            "risk_level": f["risk_level"],
            "risk_score": 20.0,
            "reason": f"Large inactive {f['file_type']} file (inactivity: {f['inactivity_score']:.0f}/100)",
            "explanation": (
                f"This {_fmt_size(f['size_bytes'])} file has not been accessed in a long time "
                f"and has an inactivity score of {f['inactivity_score']:.0f}/100. "
                "Consider archiving to external storage."
            ),
            "duplicate_group": None,
            "category": "inactive",
        }
        recommendations.append(rec)

    # 5. Log files
    logs = await fetchall(db, """
        SELECT SUM(size_bytes) as total
        FROM files
        WHERE file_type = 'log' AND risk_level = 'LOW'
    """)
    log_total = logs[0]["total"] if logs and logs[0]["total"] else 0
    if log_total > 50_000_000:
        recommendations.append({
            "action": "CLEANUP",
            "target_path": "[log files]",
            "target_type": "file_type",
            "size_bytes": int(log_total),
            "confidence": 0.82,
            "risk_level": "LOW",
            "risk_score": 12.0,
            "reason": f"Log files consuming {_fmt_size(log_total)}",
            "explanation": (
                "Application log files detected. Old logs are generally safe to remove "
                "unless you need them for debugging."
            ),
            "duplicate_group": None,
            "category": "log",
        })

    # Deduplicate and sort by size descending
    recommendations.sort(key=lambda r: r["size_bytes"], reverse=True)

    # Persist to DB
    for r in recommendations:
        await db.execute("""
            INSERT INTO recommendations(
                action, target_path, target_type, size_bytes, confidence,
                risk_level, risk_score, reason, explanation, duplicate_group, category
            ) VALUES(?,?,?,?,?,?,?,?,?,?,?)
        """, (
            r["action"], r["target_path"], r["target_type"],
            r["size_bytes"], r["confidence"], r["risk_level"],
            r["risk_score"], r["reason"], r["explanation"],
            r.get("duplicate_group"), r.get("category"),
        ))

    await db.commit()

    # Fetch with IDs
    return await fetchall(db, """
        SELECT * FROM recommendations
        WHERE status = 'PENDING'
        ORDER BY size_bytes DESC
    """)


def compute_storage_health_score(
    utilization_pct: float,
    duplicate_pct: float,
    anomaly_count: int,
    days_until_90: int,
) -> int:
    """
    Compute Storage Health Score 0–100.
    100 = perfectly healthy, 0 = critical.
    """
    score = 100.0

    # Utilization penalty
    if utilization_pct > 95:
        score -= 40
    elif utilization_pct > 90:
        score -= 30
    elif utilization_pct > 80:
        score -= 20
    elif utilization_pct > 70:
        score -= 10

    # Duplicate penalty (% of total storage that's wasted)
    if duplicate_pct > 20:
        score -= 15
    elif duplicate_pct > 10:
        score -= 8
    elif duplicate_pct > 5:
        score -= 3

    # Anomaly penalty
    score -= min(anomaly_count * 5, 15)

    # Days until 90% penalty
    if days_until_90 <= 7:
        score -= 20
    elif days_until_90 <= 14:
        score -= 10
    elif days_until_90 <= 30:
        score -= 5

    return max(0, min(100, int(score)))


def _fmt_size(b: int) -> str:
    if b >= 1e9:
        return f"{b/1e9:.1f} GB"
    elif b >= 1e6:
        return f"{b/1e6:.1f} MB"
    elif b >= 1e3:
        return f"{b/1e3:.1f} KB"
    return f"{b} B"


def json_paths(paths: list[str]) -> str:
    import json
    if len(paths) == 1:
        return paths[0]
    return json.dumps(paths)
